// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrtfJ8IZiExP8qui4E0oYtVgCF3UJHPQ',
    appId: '1:961957914773:web:8303af2cbdf82be639139c',
    messagingSenderId: '961957914773',
    projectId: 'fatoora-6b192',
    authDomain: 'fatoora-6b192.firebaseapp.com',
    storageBucket: 'fatoora-6b192.firebasestorage.app',
    measurementId: 'G-R8RMC24ENW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTf7PY1nM5lzFWg_ua10A2LYBkaDCBUO8',
    appId: '1:961957914773:android:84ae3597a1dea12439139c',
    messagingSenderId: '961957914773',
    projectId: 'fatoora-6b192',
    storageBucket: 'fatoora-6b192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzcV98DzpyG-g8ijCegYPYz7ew1hbGrgA',
    appId: '1:961957914773:ios:30b473f930c6a52339139c',
    messagingSenderId: '961957914773',
    projectId: 'fatoora-6b192',
    storageBucket: 'fatoora-6b192.firebasestorage.app',
    iosBundleId: 'com.example.fatoora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzcV98DzpyG-g8ijCegYPYz7ew1hbGrgA',
    appId: '1:961957914773:ios:30b473f930c6a52339139c',
    messagingSenderId: '961957914773',
    projectId: 'fatoora-6b192',
    storageBucket: 'fatoora-6b192.firebasestorage.app',
    iosBundleId: 'com.example.fatoora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALrtfJ8IZiExP8qui4E0oYtVgCF3UJHPQ',
    appId: '1:961957914773:web:bdcca6eff279795439139c',
    messagingSenderId: '961957914773',
    projectId: 'fatoora-6b192',
    authDomain: 'fatoora-6b192.firebaseapp.com',
    storageBucket: 'fatoora-6b192.firebasestorage.app',
    measurementId: 'G-MP1S3TH16W',
  );
}
